# Generated by Django 2.1.2 on 2018-10-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='xxx', max_length=200),
            preserve_default=False,
        ),
    ]
