version: '2.1'

services:
  mongodb:
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    image: mongo:latest
    ports:
      - "27017:27017"
  comment:
    build: .
    container_name: comments
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    entrypoint: /entrypoint.sh

    
